- name: Test Patch
  hosts: all
  become: yes
  tasks:
    - name: Run apt update
      apt:
        update_cache: yes

    - name: Write semaphore proof file
      copy:
        content: "Semaphore was here at {{ ansible_date_time.iso8601 }}"
        dest: /tmp/semaphore-proof.txt
